server:
  port: 8091

spring:
  application:
    name: banking-user-service
    data:
        mongodb:
            uri: mongodb+srv://xvris:xvris@cluster0.bpun4.mongodb.net/apibanca

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true
info:
  application:
    name : banking-user-service
    Description : This is a Microservice to manage clients
    artifact : banking-user-service
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka

#apiclient:
#  uri: http://localhost:8092
#microservice-accounts:
#  uri: /api/accounts/findByClientId

resilience4j:
  circuitbreaker.:
    instances:
      saveClientCB:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
      getClientCB:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true

resilience4j.timelimiter:
    instances:
      saveClientCB:
        timeoutDuration: 2000ms
        cancelRunningFuture: true
      getClientCB:
        timeoutDuration: 2000ms
        cancelRunningFuture: true
